import { strict as assert } from 'node:assert';
import { mkdtemp, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || '/Users/nikash/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const profile=await mkdtemp(join(tmpdir(),'gym-browser-'));
const origin=process.env.GYM_TEST_URL||'http://localhost:4173';
const launch=offline=>chromium.launchPersistentContext(profile,{headless:true,executablePath:process.env.GYM_BROWSER_EXECUTABLE||'/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',timezoneId:'America/New_York',viewport:{width:390,height:844},offline});
let context=await launch(false), page=context.pages()[0];
const errors=[];const track=p=>p.on('pageerror',e=>errors.push(e.message));track(page);
const wait=async(fn)=>{for(let i=0;i<100;i++){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('Condition timed out');};
const snap=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open(localStorage.getItem('gym-owner')?'gym-notebook-'+localStorage.getItem('gym-owner'):'gym-notebook',1);r.onsuccess=()=>{const db=r.result;const q=db.transaction('notebook').objectStore('notebook').get('state');q.onsuccess=()=>{resolve(q.result);db.close()};q.onerror=()=>reject(q.error)}}));
const synced=()=>wait(async()=>{const s=await snap();return s?.data&&s.pending.length===0&&await page.locator('.save-status').innerText()==='Synced'});
const input=name=>page.getByRole('spinbutton',{name,exact:true});
const pass=message=>console.log(`PASS ${message}`);
try{
 await page.goto(origin); if(process.env.GYM_TEST_PASSWORD){await page.getByLabel('Account name',{exact:true}).first().fill(process.env.GYM_TEST_USERNAME||'test-owner');await page.getByLabel('Password',{exact:true}).first().fill(process.env.GYM_TEST_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).first().click();} await page.getByRole('heading',{name:'Legs',exact:true}).waitFor(); await synced();
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await wait(()=>page.evaluate(()=>!!navigator.serviceWorker.controller));
 assert.equal((await snap()).data.program.length,7);pass('online program load and installed service worker');
 for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.locator('body').innerText().then(t=>t.includes('—')),false);pass('phone widths 320/390/430 have no horizontal scrolling or em dashes');
 await context.setOffline(true);
 await page.getByRole('button',{name:'kg',exact:true}).click();
 await input('Back Squat set 1 weight').fill('20');
 await input('Back Squat set 1 reps').fill('8');
 await page.getByRole('checkbox',{name:'Complete Back Squat set 1',exact:true}).check();
 await wait(async()=>{const s=await snap();return s.data.sessions.find(s=>s.date==='2026-09-07')?.exercises[0].entries[0].completed});
 assert.equal(await page.evaluate(()=>document.activeElement.id),'set-0-1');
 await page.getByRole('tab',{name:'Body weight',exact:true}).click();
 await input('Body weight').fill('55.5'); await page.getByRole('button',{name:/^(Log|Update) weight$/}).click();
 await wait(async()=> (await snap()).data.body.some(b=>b.weightKg===55.5));
 await page.getByRole('tab',{name:'Program',exact:true}).click();
 await page.getByRole('button',{name:'Add exercise',exact:true}).click();
 await page.getByLabel('Exercise name',{exact:true}).fill('Offline Test');
 await page.getByRole('button',{name:'Apply changes',exact:true}).click();
 await wait(async()=> (await snap()).data.program[0].exercises.some(e=>e.name==='Offline Test'));
 const before=await snap();assert.ok(before.pending.length>=5);pass('offline workout, completion focus, body weight, and program edits commit to IndexedDB');
 await context.close();context=await launch(true);page=context.pages()[0];track(page);
 await page.goto(origin);await page.getByRole('heading',{name:'Legs',exact:true}).waitFor();
 await wait(async()=>!!(await snap())?.data);
 assert.deepEqual((await snap()).data,before.data);assert.equal((await snap()).pending.length,before.pending.length);pass('full browser shutdown and offline relaunch preserve data and outbox');
 await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await synced();
 const remote=await page.evaluate(()=>fetch('/api/log').then(r=>r.json()).then(v=>v.data??v));
 assert.equal(remote.body.filter(b=>b.date==='2026-09-07').length,1);
 assert.equal(remote.sessions.find(s=>s.date==='2026-09-07').exercises[0].entries[0].weightKg,20);
 // Replay the same acknowledged operation after a newer change. Receipt must stop it.
 const old=before.pending.find(op=>op.action.type==='body');
 const fresh={id:crypto.randomUUID(),action:{type:'body',date:old.action.date,weightKg:56}};
 await page.evaluate(async({old,fresh})=>{for(const op of [fresh,old,old]){const r=await fetch('/api/log',{method:'POST',headers:{'Content-Type':'application/json','X-Notebook-Owner':localStorage.getItem('gym-owner')||''},body:JSON.stringify(op)});if(!r.ok)throw Error('Replay failed')}},{old,fresh});
 const replay=await page.evaluate(()=>fetch('/api/log').then(r=>r.json()).then(v=>v.data??v));assert.equal(replay.body.find(b=>b.date===old.action.date).weightKg,56);pass('reconnect sync has no duplicates and acknowledged replay cannot overwrite newer data');
 await page.reload();await synced();assert.equal((await snap()).data.body.find(b=>b.date===old.action.date).weightKg,56);pass('refresh confirms server persistence');
 await page.getByLabel('Workout date',{exact:true}).fill('2026-09-14');await input('Back Squat set 1 weight').waitFor();
 await wait(async()=>await input('Back Squat set 1 weight').inputValue()==='20');
 assert.equal(await input('Back Squat set 1 reps').inputValue(),'8');assert.equal(await page.getByRole('checkbox',{name:'Complete Back Squat set 1',exact:true}).isChecked(),false);
 await page.getByRole('button',{name:'lb',exact:true}).click();assert.equal(await input('Back Squat set 1 weight').inputValue(),'44.1');await page.getByRole('button',{name:'kg',exact:true}).click();assert.equal(await input('Back Squat set 1 weight').inputValue(),'20');pass('later workout prefills prior performance; unit conversion preserves kilograms');
 await page.locator('.app-tools>summary').click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export backup',exact:true}).click();const download=await downloadPromise;const backupPath=join(profile,'backup.json');await download.saveAs(backupPath);
 const backup=JSON.parse(await readFile(backupPath,'utf8'));assert.equal(backup.format,'gym-notebook');
 await page.getByRole('tab',{name:'Body weight',exact:true}).click();await page.getByRole('button',{name:'Delete weight 2026-09-07',exact:true}).click();await synced();
 assert.equal((await snap()).data.body.some(b=>b.date==='2026-09-07'),false);
 await page.locator('input[type=file]').setInputFiles(backupPath);await page.getByRole('button',{name:'Restore this backup',exact:true}).click();await synced();assert.equal((await snap()).data.body.find(b=>b.date==='2026-09-07').weightKg,56);
 await page.locator('input[type=file]').setInputFiles(backupPath);await page.getByRole('button',{name:'Restore this backup',exact:true}).click();await synced();assert.equal((await snap()).data.body.filter(b=>b.date==='2026-09-07').length,1);pass('backup export, deletion, restore and repeated restore do not duplicate records');
 await context.setOffline(true);await page.getByRole('button',{name:'Delete weight 2026-09-07',exact:true}).click();
 await page.getByRole('tab',{name:'Program',exact:true}).click();await page.getByRole('button',{name:'Offline Test 3 sets',exact:false}).click();await page.getByRole('button',{name:'Remove exercise',exact:true}).click();
 await wait(async()=>!(await snap()).data.program[0].exercises.some(e=>e.name==='Offline Test'));
 await page.reload();assert.equal((await snap()).data.body.length,0);await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await synced();pass('offline body and program deletions survive refresh and synchronize');
 await page.screenshot({path:'outputs/browser-phone.png',fullPage:true});
 assert.deepEqual(errors,[]);pass('no browser runtime errors');
 await writeFile('outputs/browser-results.json',JSON.stringify({passed:true,profile,errors},null,2));
}finally{await context.close()}
